linters:
  disable-all: true
  enable:
  # default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  # non-default additions
    - bodyclose
    - errname
    - gocritic
    - godot
    #- gofmt
    - gofumpt
    - goimports
    - misspell
