global:
  scrape_interval: 15s

scrape_configs:
  - job_name: arbiter
    static_configs:
      - targets: ["host.docker.internal:8888"]
  - job_name: arbiter-locksmith
    metrics_path: "/metrics-locksmith"
    static_configs:
      - targets: ["host.docker.internal:8888"]
